services:
  mysql:
    image: mysql:8.4
    container_name: mysql_db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: Msd1213
      MYSQL_DATABASE: worldcup_bot
      MYSQL_USER: bot_user
      MYSQL_PASSWORD: Msd1213

    ports:
      - "45278:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pMsd1213"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: